HAI 1.2
CAN HAS STDIO?
I HAS A VAR1
I HAS A VAR2
VAR1 R 5
VAR2 R 7
I HAS A SUM
I HAS A DIFF
SUM R SUM OF VAR1 AN VAR2
DIFF R DIFF OF VAR1 AN VAR2
VISIBLE "SUM: " SUM
VISIBLE "DIFFERENCE: " DIFF
KTHXBYE
