HAI 1.2
  CAN HAS STDIO?
  I HAS A VAR
  VAR R 1
  IM IN YR LOOP
    VISIBLE "COUNTING: " VAR
    VAR R SUM OF VAR AN 1
    BOTH SAEM VAR AN 11, O RLY?
      YA RLY, GTFO
    OIC
  IM OUTTA YR LOOP
KTHXBYE
